ServerEvents.recipes(event =>{
    //event to remove recipes itens multicolored
    const colors = ['white', 'light_gray','light_blue', 'gray', 'black', 'brown', 'red', 'orange', 'yellow', 'lime', 'green', 'cyan', 'light_blue', 'blue', 'purple', 'magenta', 'pink'];
    colors.forEach(color => {
        event.remove({id: `botanypotstiers:crafting/creative_${color}_concrete_botany_pot`})
        event.remove({id: `botanypots:botanypots/crafting/${color}_glazed_terracotta_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_glazed_terracotta_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_glazed_terracotta_botany_pot_2`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_terracotta_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_concrete_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_glazed_terracotta_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/creative_${color}_terracotta_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/ultra_${color}_terracotta_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/ultra_${color}_concrete_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/ultra_${color}_glazed_terracotta_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/elite_${color}_terracotta_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/elite_${color}_concrete_compact_hopper_botany_pot`})
        event.remove({id: `botanypotstiers:crafting/elite_${color}_glazed_terracotta_compact_hopper_botany_pot`})
    })
    //events to remove recipes
    event.remove({id: "mifa:dissolution_chamber/processing_addon_2"})
    event.remove({id: "mifa:dissolution_chamber/speed_addon_3"})
    event.remove({id: "mifa:dissolution_chamber/efficiency_addon_3"})
    event.remove({output: "mekaminers:create_age_2/mechanical_crafter"})
    event.remove({output: "createaddition:electric_motor"})
    event.remove({output: "create_new_age:basic_motor"})
    event.remove({output: "ars_technica:source_engine"})
    event.remove({output: "enderio:player_token"})
    event.remove({id: "botanypotstiers:crafting/creative_terracotta_botany_pot_2"})
    event.remove({id: "botanypotstiers:crafting/creative_terracotta_compact_hopper_botany_pot_2"})
    event.remove({id: "botanypotstiers:crafting/ultra_terracotta_hopper_botany_pot"})
    event.remove({id: "botanypotstiers:crafting/ultra_terracotta_compact_hopper_botany_pot_2"})
    event.remove({id: "botanypotstiers:crafting/elite_terracotta_hopper_botany_pot"})
    event.remove({id: "botanypotstiers:crafting/elite_terracotta_compact_hopper_botany_pot_2"})
    event.remove({id: "botanypots:botanypots/crafting/terracotta_compact_hopper_botany_pot"})
    event.remove({id: "botanypots:botanypots/crafting/terracotta_hopper_botany_pot"})
    event.remove({id: "botanypotstiers:crafting/creative_terracotta_hopper_botany_pot"})
    event.remove({id: "botanypotstiers:crafting/creative_terracotta_compact_hopper_botany_pot_3"})
    event.remove({id: "botanypotstiers:crafting/elite_terracotta_compact_hopper_botany_pot_3"})
    event.remove({id: "botanypotstiers:crafting/ultra_terracotta_compact_hopper_botany_pot_3"})
})